/**
 * PageNotGenerated Component (DEV ONLY)
 *
 * This component is shown in development when a user navigates to a page
 * that hasn't been generated by the AI yet. It provides a helpful message
 * instead of a generic 404 error.
 *
 * This component should only be rendered in development mode.
 */

import { Link } from "react-router";

interface PageNotGeneratedProps {
  pathname?: string;
}

export default function PageNotGenerated({ pathname }: PageNotGeneratedProps) {
  return (
    <div className="flex min-h-[60vh] flex-col items-center justify-center px-4 py-16">
      <div className="max-w-md text-center">
        {/* Icon */}
        <div className="mx-auto mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-amber-100">
          <svg
            className="h-10 w-10 text-amber-600"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={1.5}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
            />
          </svg>
        </div>

        {/* Title */}
        <h1 className="mb-3 text-2xl font-bold text-gray-900">
          Page Not Generated Yet
        </h1>

        {/* Message */}
        <p className="mb-6 text-gray-600">
          This page hasn't been created by the AI assistant yet. Use the chat to
          ask the assistant to generate this page for you.
        </p>

        {/* Path info */}
        {pathname && (
          <p className="mb-6 rounded-lg bg-gray-100 px-4 py-2 font-mono text-sm text-gray-700">
            {pathname}
          </p>
        )}

        {/* Dev mode badge */}
        <div className="mb-6 inline-flex items-center gap-1.5 rounded-full bg-purple-100 px-3 py-1 text-xs font-medium text-purple-700">
          <span className="h-1.5 w-1.5 rounded-full bg-purple-500" />
          Development Mode Only
        </div>

        {/* Back link */}
        <div>
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-sm font-medium text-blue-600 hover:text-blue-800"
          >
            <svg
              className="h-4 w-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M10 19l-7-7m0 0l7-7m-7 7h18"
              />
            </svg>
            Back to Homepage
          </Link>
        </div>
      </div>
    </div>
  );
}
